### ISSUE TITLE
Reload script on .blend load?

### ISSUE THREAD

**Issue by kilbee** [wisaac407/blender-script-watcher#1]
I've been thinking if it would be good idea to reload script on loading new .blend file. 
Currently you have to force refresh it manually on load (if you saved your .blend with script watcher on; you have to turn watching off and on again).
I was about to do it but then I had second thoughts if this would be potentially dangerous/unwanted behaviour?

Anyway it would be easy to implement via [bpy.app.handlers](http://www.blender.org/api/blender_python_api_2_60_6/bpy.app.handlers.html)

**Comment by wisaac407** [comment]
The fact that it says it's watching a script when it's not is defiantly a problem, I've been trying to decide what the best way to go about fixing it is.

If you're not familiar with the code, this is caused because Script Watcher is a modal operator, and since there is no way to query the state of a modal, it needs to be stored in it's own variable (set to true when the modal get's started, set to false when it's cancelled). The state of SW is stored in blenders data system (`scene.sw_settings.running`) causing it to be saved with the file. This means that when you open the file, according to the state variable (and the UI) SW is running, when in reality the modal hasn't been started yet.

There's two ways to fix this:
1. Reset the state to not running (making the UI match the modal)
   - Either via handlers or storing the value in a global dict.
2. Startup the Script Watcher modal (making the modal match the UI)
   - I think handlers are the only way to accomplish this.

I'm on the fence as to which is the better solution. It seems like you're proposal would be a useful feature, I'm just not entirely sure if it makes sense in all cases. Maybe there should be an option to enable it? Something like the `Register` option in the text editor?

**Comment by kilbee** [comment]
Well, I guess depends how you work with blender. For example I happen to restart blender quite often recently, to make sure all datablocks that shouldn't be there are flushed. So solution 2. would be much better in my case - simply saves time. However now that you mentioned it I do think it should be optional, so it would be possible to enable it only for certain periods.
So If there are no other problems with re-loading SW on start i think solution should be mix of both: handler triggers check if SW is (supposedly) running and another variable 'restart_on_load' , if both are True, then solution no. 2.
If only first is True, then solution no. 1.

**Comment by wisaac407** [comment]
That makes a lot of sense, I can't think of any situations where it would fail (except possibly when appending a scene from another .blend file which uses SW, because SW runs on each scene).

If you want to implement it go ahead, otherwise I'd be happy to. I'm excited to finally get this bug resolved. :smile:

**Comment by kilbee** [comment]
Ok, I've implemented it. Works ok, but check everything and maybe fit it to your style - I'm not very experienced with coding ;)

**Comment by wisaac407** [comment]
Looks really good. Only thing is, maybe it should loop through all the scenes in `bpy.data.scenes` and act on each scene, instead of just the current one in `bpy.context`.

Otherwise it looks great!

**Comment by kilbee** [comment]
Right, after all it's scene property.
I've been looking into this and it looks bit complicated or I am missing something: 
i tested how scripts work on different scenes with adding a mesh with a different script for each scene. If i simply let scripts execute on load, they all add mesh to the active scene, so you need to change scene for each script to execute. So this can be problematic with some scripts and the best way to avoid problems would be to turn off script execution for all scenes except active one? Anyway I'll look more into that later when I have some time, hopefully you'll have that sorted out by then ;D

**Comment by wisaac407** [comment]
That's a good point, it might make more scene to simply start it on the current scene and cancel it on all the other scenes (because technically SW only runs on one scene at a time anyway). It should be a pretty easy change, I'll be able to work on it later this week ;)

**Comment by wisaac407** [comment]
Okay it's fixed. 
See: d99825c6a47e444848dffcf9a4962dafa6a94a03

Thank you for your help :+1:
